service: projetovamosachina
provider:
  name: aws
  runtime: nodejs10.x
  credentials: ${file(./.env.yml):credentials}
  deploymentBucket:
    name: 'vamosaachina-backend'

custom:
  writeEnvVars:
    AWS_ACCESS_KEY_ID: ${file(./.env.yml):${opt:stage}.AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${file(./.env.yml):${opt:stage}.AWS_SECRET_ACCESS_KEY}
    TOKEN: ${file(./.env.yml):${opt:stage}.TOKEN}
    EMAIL: ${file(./.env.yml):${opt:stage}.EMAIL}
    DATABASE: ${file(./.env.yml):${opt:stage}.DATABASE}
    SANDBOX: ${file(./.env.yml):${opt:stage}.SANDBOX}
    SANDBOX_EMAIL: ${file(./.env.yml):${opt:stage}.SANDBOX_EMAIL}
    NOTIFICATIONEMAIL: ${file(./.env.yml):${opt:stage}.NOTIFICATIONEMAIL}
    NOTIFICATION_URL: ${file(./.env.yml):${opt:stage}.NOTIFICATION_URL}
    RSAKEY: ${file(./.env.yml):${opt:stage}.RSAKEY}
    ORIGIN: ${file(./.env.yml):${opt:stage}.ORIGIN}
  serverless-layers:
    packageManager: yarn
  sucrase:
    sources:
      - config.js
      - index.js
      - src/**/*.js

    transforms:
      - imports

plugins:
  - serverless-layers
  - serverless-sucrase
  - serverless-plugin-write-env-vars

functions:
  api:
    handler: index.handler
    events:
      - http: ANY {proxy+}
        cors: true
